version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - jenkins
    command: sh -c "npm install && npm run start"

volumes:
  jenkins_home: